"""Regenerate out/index.html — a static gallery of every chart PNG in out/.

    python make_index.py

Deterministic, no network, no dependencies. Safe to run after every chart.
"""
import html
import os
import re
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(ROOT, "out")

LEAGUES = {
    "pl": "Premier League",
    "laliga": "La Liga",
    "ucl": "Champions League",
    "ligue1": "Ligue 1",
    "nations-league": "Nations League",
}
ROUNDS = {"mw": "Matchweek", "j": "Jornada", "md": "Matchday"}


def label(stem):
    """'pl-mw4' -> ('Premier League', 'Matchweek 4'); unknown stems degrade gracefully."""
    league, _, rnd = stem.rpartition("-")
    if not league:
        return stem, ""
    name = LEAGUES.get(league, league.replace("-", " ").title())
    m = re.fullmatch(r"([a-z]+)(\d+)", rnd)
    if m and m.group(1) in ROUNDS:
        return name, f"{ROUNDS[m.group(1)]} {int(m.group(2))}"
    return name, rnd.replace("-", " ").title()


def main():
    pngs = [f for f in os.listdir(OUT) if f.lower().endswith(".png")]
    pngs.sort(key=lambda f: os.path.getmtime(os.path.join(OUT, f)), reverse=True)

    cards = []
    for f in pngs:
        league, rnd = label(os.path.splitext(f)[0])
        mtime = datetime.fromtimestamp(os.path.getmtime(os.path.join(OUT, f)), timezone.utc)
        kb = os.path.getsize(os.path.join(OUT, f)) // 1024
        cards.append(
            f'''      <a class="card" href="{html.escape(f)}">
        <img src="{html.escape(f)}" alt="{html.escape(league)} {html.escape(rnd)}" loading="lazy">
        <div class="meta">
          <span class="league">{html.escape(league)}</span>
          <span class="round">{html.escape(rnd)}</span>
          <span class="stamp">{mtime:%Y-%m-%d %H:%M} UTC · {kb} KB</span>
        </div>
      </a>'''
        )

    body = "\n".join(cards) if cards else '      <p class="empty">No charts in out/ yet.</p>'
    built = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    page = f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Futbol Charts</title>
<style>
  :root {{
    --bg: #0d1117; --panel: #161b22; --line: #2a3139;
    --fg: #e6edf3; --dim: #8b949e; --accent: #3fb950;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0; padding: 24px 16px 64px;
    background: var(--bg); color: var(--fg);
    font: 15px/1.5 ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif;
  }}
  header {{ max-width: 1100px; margin: 0 auto 28px; }}
  h1 {{ margin: 0 0 6px; font-size: 22px; letter-spacing: -0.01em; }}
  h1 span {{ color: var(--accent); }}
  .sub {{ color: var(--dim); font-size: 13px; }}
  .grid {{
    max-width: 1100px; margin: 0 auto;
    display: grid; gap: 16px;
    grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
  }}
  .card {{
    display: block; text-decoration: none; color: inherit;
    background: var(--panel); border: 1px solid var(--line); border-radius: 10px;
    overflow: hidden; transition: border-color .15s ease, transform .15s ease;
  }}
  .card:hover, .card:focus-visible {{ border-color: var(--accent); transform: translateY(-2px); }}
  .card img {{ display: block; width: 100%; height: auto; background: #fff; }}
  .meta {{ padding: 12px 14px; display: grid; gap: 2px; }}
  .league {{ font-weight: 600; }}
  .round {{ color: var(--accent); font-size: 13px; }}
  .stamp {{ color: var(--dim); font-size: 12px; font-variant-numeric: tabular-nums; }}
  .empty {{ color: var(--dim); }}
  footer {{ max-width: 1100px; margin: 32px auto 0; color: var(--dim); font-size: 12px; }}
</style>
</head>
<body>
  <header>
    <h1>Futbol <span>Charts</span></h1>
    <p class="sub">{len(pngs)} chart{"" if len(pngs) == 1 else "s"} · newest first · tap any chart for full size</p>
  </header>
  <div class="grid">
{body}
  </div>
  <footer>Generated by make_index.py — {built}</footer>
</body>
</html>
'''
    path = os.path.join(OUT, "index.html")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(page)
    print(f"Wrote out/index.html — {len(pngs)} chart(s)")


if __name__ == "__main__":
    main()
